/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// llm.ts
var llm_exports = {};
__export(llm_exports, {
  callLLMForIngest: () => callLLMForIngest,
  callLLMForLint: () => callLLMForLint,
  callLLMForQuery: () => callLLMForQuery
});
async function callLLMForIngest(settings, sourceContent, sourceFilename) {
  const userPrompt = `Source filename: ${sourceFilename}

Source Content:
${sourceContent}`;
  if (settings.provider === "openai") {
    return callOpenAIIngest(settings, userPrompt);
  } else if (settings.provider === "anthropic") {
    return callAnthropicIngest(settings, userPrompt);
  } else if (settings.provider === "ollama") {
    return callOllamaIngest(settings, userPrompt);
  } else {
    throw new Error(`Unsupported provider: ${settings.provider}`);
  }
}
async function callLLMForLint(settings, indexContent) {
  const systemPrompt = `You are an expert knowledge base health inspector. You are given the current index of the user's Obsidian wiki.
Your job is to look for:
- Potential contradictions between pages
- Orphan concepts that should probably have their own pages
- Missing cross-references
- Broad topics that should be broken down

Provide a bulleted list of actionable recommendations. Be concise and use standard Markdown.`;
  if (settings.provider === "openai") {
    return callOpenAIQuery(settings, systemPrompt, "Please review the following index and provide health recommendations:\n" + indexContent);
  } else if (settings.provider === "anthropic") {
    return callAnthropicQuery(settings, systemPrompt, "Please review the following index and provide health recommendations:\n" + indexContent);
  } else if (settings.provider === "ollama") {
    return callOllamaQuery(settings, systemPrompt, "Please review the following index and provide health recommendations:\n" + indexContent);
  } else {
    throw new Error(`Unsupported provider: ${settings.provider}`);
  }
}
async function callLLMForQuery(settings, query, indexContent) {
  const systemPrompt = `You are an expert knowledge base assistant. You are given the current index of the user's Obsidian wiki.
Your job is to answer the user's query based on the index or general knowledge, and optionally suggest they create new pages.
Whenever you mention a topic that exists in the index, use Obsidian [[Wikilinks]].

Here is the current Wiki Index:
${indexContent}
`;
  if (settings.provider === "openai") {
    return callOpenAIQuery(settings, systemPrompt, query);
  } else if (settings.provider === "anthropic") {
    return callAnthropicQuery(settings, systemPrompt, query);
  } else if (settings.provider === "ollama") {
    return callOllamaQuery(settings, systemPrompt, query);
  } else {
    throw new Error(`Unsupported provider: ${settings.provider}`);
  }
}
async function callOllamaIngest(settings, userPrompt) {
  let endpoint = settings.ollamaEndpoint || "http://localhost:11434";
  if (endpoint.endsWith("/")) {
    endpoint = endpoint.slice(0, -1);
  }
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${endpoint}/api/chat`,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: INGEST_SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      stream: false,
      format: "json",
      options: {
        temperature: 0.2
      }
    })
  });
  if (response.status !== 200) {
    throw new Error(`Ollama Error: ${response.text}`);
  }
  const data = response.json;
  const content = data.message.content;
  try {
    return JSON.parse(content);
  } catch (e) {
    throw new Error("Failed to parse JSON from Ollama response");
  }
}
async function callOpenAIIngest(settings, userPrompt) {
  if (!settings.apiKey)
    throw new Error("OpenAI API key is missing");
  const response = await (0, import_obsidian2.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${settings.apiKey}`
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: INGEST_SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      response_format: { type: "json_object" },
      temperature: 0.2
    })
  });
  if (response.status !== 200) {
    throw new Error(`OpenAI Error: ${response.text}`);
  }
  const data = response.json;
  const content = data.choices[0].message.content;
  try {
    return JSON.parse(content);
  } catch (e) {
    throw new Error("Failed to parse JSON from OpenAI response");
  }
}
async function callAnthropicIngest(settings, userPrompt) {
  if (!settings.apiKey)
    throw new Error("Anthropic API key is missing");
  const response = await (0, import_obsidian2.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": settings.apiKey,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: settings.model,
      system: INGEST_SYSTEM_PROMPT,
      messages: [
        { role: "user", content: userPrompt }
      ],
      max_tokens: 4e3,
      temperature: 0.2
    })
  });
  if (response.status !== 200) {
    throw new Error(`Anthropic Error: ${response.text}`);
  }
  const data = response.json;
  const content = data.content[0].text;
  let cleanContent = content.trim();
  if (cleanContent.startsWith("```json")) {
    cleanContent = cleanContent.replace(/^```json/, "").replace(/```$/, "").trim();
  } else if (cleanContent.startsWith("```")) {
    cleanContent = cleanContent.replace(/^```/, "").replace(/```$/, "").trim();
  }
  try {
    return JSON.parse(cleanContent);
  } catch (e) {
    throw new Error("Failed to parse JSON from Anthropic response");
  }
}
async function callOllamaQuery(settings, systemPrompt, userPrompt) {
  let endpoint = settings.ollamaEndpoint || "http://localhost:11434";
  if (endpoint.endsWith("/")) {
    endpoint = endpoint.slice(0, -1);
  }
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${endpoint}/api/chat`,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      stream: false,
      options: {
        temperature: 0.7
      }
    })
  });
  if (response.status !== 200) {
    throw new Error(`Ollama Error: ${response.text}`);
  }
  return response.json.message.content;
}
async function callOpenAIQuery(settings, systemPrompt, userPrompt) {
  if (!settings.apiKey)
    throw new Error("OpenAI API key is missing");
  const response = await (0, import_obsidian2.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${settings.apiKey}`
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`OpenAI Error: ${response.text}`);
  }
  return response.json.choices[0].message.content;
}
async function callAnthropicQuery(settings, systemPrompt, userPrompt) {
  if (!settings.apiKey)
    throw new Error("Anthropic API key is missing");
  const response = await (0, import_obsidian2.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": settings.apiKey,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: settings.model,
      system: systemPrompt,
      messages: [
        { role: "user", content: userPrompt }
      ],
      max_tokens: 4e3,
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`Anthropic Error: ${response.text}`);
  }
  return response.json.content[0].text;
}
var import_obsidian2, INGEST_SYSTEM_PROMPT;
var init_llm = __esm({
  "llm.ts"() {
    import_obsidian2 = require("obsidian");
    INGEST_SYSTEM_PROMPT = `You are an expert knowledge base maintainer acting as an "LLM Wiki Forge".
Your job is to read a raw source document, extract its key information, and integrate it into a personal Obsidian wiki.

You MUST follow these rules carefully:
- Always use standard Obsidian \`[[Wikilinks]]\` for concepts, people, and topics.
- Always include valid YAML Frontmatter at the very top of \`wikiContent\` starting with \`---\` and ending with \`---\`.
- In the Frontmatter, include fields like \`type: source-summary\`, \`tags: [...]\`, and \`source: [filename]\`.
- Make the summary structured using Markdown headings (e.g., \`## Core Idea\`, \`## Key Takeaways\`).

You should return your answer EXACTLY as a JSON object with four keys:
1. "suggestedFilename": A short, hyphen-separated filename for the new wiki page (e.g., "concept-attention-mechanism"). Do NOT include the .md extension.
2. "wikiContent": The full markdown content of the new wiki page (including frontmatter and Obsidian wikilinks).
3. "logEntry": A one-line string to append to the chronological log.md file. Format: "- [YYYY-MM-DD] Ingested | [Source Title] -> [[suggestedFilename]]"
4. "indexEntry": A one-line string to insert into the index.md file. Format: "- [[suggestedFilename]]: A short one-sentence summary of what this page is about."

CRITICAL: Return ONLY valid JSON. Do not include markdown codeblocks (\`\`\`json) or any conversational text before or after the JSON.
`;
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LLMWikiForgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// view.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_LLM_WIKI = "llm-wiki-view";
var LLMWikiView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTab = "ingest";
    this.chatHistory = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LLM_WIKI;
  }
  getDisplayText() {
    return "LLM Wiki Forge";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("h3", { text: "LLM Wiki Forge" });
    const tabsContainer = container.createDiv({ cls: "llm-wiki-forge-tabs" });
    const tabIngest = tabsContainer.createEl("div", { cls: `llm-wiki-forge-tab ${this.activeTab === "ingest" ? "active" : ""}`, text: "Ingest" });
    const tabQuery = tabsContainer.createEl("div", { cls: `llm-wiki-forge-tab ${this.activeTab === "query" ? "active" : ""}`, text: "Query" });
    const tabLint = tabsContainer.createEl("div", { cls: `llm-wiki-forge-tab ${this.activeTab === "lint" ? "active" : ""}`, text: "Lint" });
    const contentContainer = container.createDiv({ cls: "llm-wiki-forge-content-container" });
    const renderActiveTab = () => {
      contentContainer.empty();
      tabIngest.classList.toggle("active", this.activeTab === "ingest");
      tabQuery.classList.toggle("active", this.activeTab === "query");
      tabLint.classList.toggle("active", this.activeTab === "lint");
      if (this.activeTab === "ingest") {
        this.renderIngestTab(contentContainer);
      } else if (this.activeTab === "query") {
        this.renderQueryTab(contentContainer);
      } else if (this.activeTab === "lint") {
        this.renderLintTab(contentContainer);
      }
    };
    tabIngest.onclick = () => {
      this.activeTab = "ingest";
      renderActiveTab();
    };
    tabQuery.onclick = () => {
      this.activeTab = "query";
      renderActiveTab();
    };
    tabLint.onclick = () => {
      this.activeTab = "lint";
      renderActiveTab();
    };
    renderActiveTab();
  }
  async renderIngestTab(container) {
    container.empty();
    const { sourceFolder } = this.plugin.settings;
    container.createEl("p", { text: `Sources from: ${sourceFolder}` });
    const files = this.app.vault.getFiles().filter((file) => file.path.startsWith(sourceFolder + "/"));
    if (files.length === 0) {
      container.createEl("p", { text: "No source files found." });
      return;
    }
    const list = container.createDiv();
    for (const file of files) {
      const listItem = list.createDiv({ cls: "llm-wiki-source-item" });
      listItem.style.display = "flex";
      listItem.style.justifyContent = "space-between";
      listItem.style.alignItems = "center";
      const nameSpan = listItem.createEl("span", { text: file.name });
      nameSpan.style.cursor = "pointer";
      nameSpan.onclick = () => {
        this.app.workspace.getLeaf(false).openFile(file);
      };
      const actionDiv = listItem.createDiv();
      const statusSpan = actionDiv.createEl("span", { text: "", cls: "ingest-status" });
      statusSpan.style.marginRight = "8px";
      statusSpan.style.fontSize = "0.8em";
      statusSpan.style.color = "var(--text-muted)";
      const ingestBtn = actionDiv.createEl("button", { text: "Ingest" });
      ingestBtn.onclick = async () => {
        ingestBtn.disabled = true;
        statusSpan.innerText = "Reading...";
        try {
          await this.plugin.ingestSource(file, (status) => {
            statusSpan.innerText = status;
          });
          statusSpan.innerText = "Done";
          statusSpan.style.color = "var(--text-success)";
        } catch (e) {
          console.error("Ingest failed", e);
          statusSpan.innerText = "Failed";
          statusSpan.style.color = "var(--text-error)";
        } finally {
          ingestBtn.disabled = false;
          ingestBtn.innerText = "Re-Ingest";
        }
      };
    }
  }
  async renderQueryTab(container) {
    container.empty();
    const messagesContainer = container.createDiv({ cls: "llm-wiki-chat-messages" });
    for (const msg of this.chatHistory) {
      messagesContainer.createDiv({
        cls: `llm-wiki-chat-message ${msg.role}`,
        text: msg.content
      });
    }
    const inputContainer = container.createDiv({ cls: "llm-wiki-chat-input-container" });
    inputContainer.style.display = "flex";
    inputContainer.style.gap = "8px";
    inputContainer.style.marginTop = "auto";
    const inputEl = inputContainer.createEl("textarea", { cls: "llm-wiki-chat-input" });
    inputEl.placeholder = "Ask your wiki something...";
    inputEl.style.flexGrow = "1";
    inputEl.style.resize = "vertical";
    const sendBtn = inputContainer.createEl("button", { text: "Send" });
    const handleSend = async () => {
      const text = inputEl.value.trim();
      if (!text)
        return;
      inputEl.value = "";
      sendBtn.disabled = true;
      this.chatHistory.push({ role: "user", content: text });
      messagesContainer.createDiv({ cls: "llm-wiki-chat-message user", text });
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
      const assistantMsgDiv = messagesContainer.createDiv({ cls: "llm-wiki-chat-message assistant", text: "Thinking..." });
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
      await this.plugin.handleQuery(text, (response) => {
        assistantMsgDiv.innerText = response;
        this.chatHistory.push({ role: "assistant", content: response });
        messagesContainer.scrollTop = messagesContainer.scrollHeight;
      });
      sendBtn.disabled = false;
    };
    sendBtn.onclick = handleSend;
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    });
  }
  async renderLintTab(container) {
    container.empty();
    container.createEl("p", { text: "Run a Health Check on your Wiki to find contradictions, orphan pages, and missing links." });
    const btnDiv = container.createDiv();
    btnDiv.style.marginBottom = "16px";
    const runBtn = btnDiv.createEl("button", { text: "Run Health Check" });
    const resultsContainer = container.createDiv({ cls: "llm-wiki-lint-results" });
    resultsContainer.style.whiteSpace = "pre-wrap";
    resultsContainer.style.backgroundColor = "var(--background-secondary)";
    resultsContainer.style.padding = "12px";
    resultsContainer.style.borderRadius = "8px";
    resultsContainer.style.display = "none";
    runBtn.onclick = async () => {
      runBtn.disabled = true;
      runBtn.innerText = "Analyzing...";
      resultsContainer.style.display = "block";
      resultsContainer.innerText = "Reading index and consulting LLM...";
      await this.plugin.handleLint((response) => {
        resultsContainer.innerText = response;
      });
      runBtn.disabled = false;
      runBtn.innerText = "Run Health Check";
    };
  }
  async onClose() {
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  provider: "openai",
  model: "gpt-4o-mini",
  ollamaEndpoint: "http://localhost:11434",
  sourceFolder: "_source",
  wikiFolder: "wiki",
  indexFile: "wiki/index.md",
  logFile: "wiki/log.md"
};
var LLMWikiForgePlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("Loading LLM Wiki Forge Plugin");
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_LLM_WIKI,
      (leaf) => new LLMWikiView(leaf, this)
    );
    this.addRibbonIcon("library", "Open LLM Wiki Forge", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-llm-wiki-forge-view",
      name: "Open LLM Wiki Forge view",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new LLMWikiForgeSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_LLM_WIKI);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_LLM_WIKI, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async handleLint(onUpdate) {
    try {
      const { callLLMForLint: callLLMForLint2 } = await Promise.resolve().then(() => (init_llm(), llm_exports));
      let indexContent = "Index file not found or empty.";
      const indexFile = this.app.vault.getAbstractFileByPath(this.settings.indexFile);
      if (indexFile) {
        indexContent = await this.app.vault.read(indexFile);
      } else {
        onUpdate("No index file found to analyze.");
        return;
      }
      const response = await callLLMForLint2(this.settings, indexContent);
      onUpdate(response);
    } catch (e) {
      console.error("Lint error:", e);
      onUpdate(`Error: ${e.message}`);
    }
  }
  async handleQuery(query, onUpdate) {
    try {
      const { callLLMForQuery: callLLMForQuery2 } = await Promise.resolve().then(() => (init_llm(), llm_exports));
      let indexContent = "Index file not found or empty.";
      const indexFile = this.app.vault.getAbstractFileByPath(this.settings.indexFile);
      if (indexFile) {
        indexContent = await this.app.vault.read(indexFile);
      }
      const response = await callLLMForQuery2(this.settings, query, indexContent);
      onUpdate(response);
    } catch (e) {
      console.error("Query error:", e);
      onUpdate(`Error: ${e.message}`);
    }
  }
  async ingestSource(file, onStatus) {
    new import_obsidian3.Notice(`Ingesting ${file.name}...`);
    if (onStatus)
      onStatus("Reading File...");
    try {
      const content = await this.app.vault.read(file);
      const { callLLMForIngest: callLLMForIngest2 } = await Promise.resolve().then(() => (init_llm(), llm_exports));
      if (onStatus)
        onStatus("Calling LLM...");
      const result = await callLLMForIngest2(this.settings, content, file.name);
      if (onStatus)
        onStatus("Writing to Wiki...");
      const wikiFolderPath = this.settings.wikiFolder;
      if (!this.app.vault.getAbstractFileByPath(wikiFolderPath)) {
        await this.app.vault.createFolder(wikiFolderPath);
      }
      const newFilePath = `${wikiFolderPath}/${result.suggestedFilename}.md`;
      let wikiFile = this.app.vault.getAbstractFileByPath(newFilePath);
      if (wikiFile) {
        new import_obsidian3.Notice(`Overwriting existing ${newFilePath}`);
        await this.app.vault.modify(wikiFile, result.wikiContent);
      } else {
        wikiFile = await this.app.vault.create(newFilePath, result.wikiContent);
      }
      const logFilePath = this.settings.logFile;
      let logFile = this.app.vault.getAbstractFileByPath(logFilePath);
      const logLine = result.logEntry.replace("[YYYY-MM-DD]", (/* @__PURE__ */ new Date()).toISOString().split("T")[0]) + "\n";
      if (logFile) {
        await this.app.vault.append(logFile, logLine);
      } else {
        const logParts = logFilePath.split("/");
        if (logParts.length > 1) {
          const logFolder = logParts.slice(0, -1).join("/");
          if (!this.app.vault.getAbstractFileByPath(logFolder)) {
            await this.app.vault.createFolder(logFolder);
          }
        }
        await this.app.vault.create(logFilePath, "# Ingestion Log\n\n" + logLine);
      }
      const indexFilePath = this.settings.indexFile;
      let indexFile = this.app.vault.getAbstractFileByPath(indexFilePath);
      const indexLine = result.indexEntry + "\n";
      if (indexFile) {
        await this.app.vault.append(indexFile, indexLine);
      } else {
        const indexParts = indexFilePath.split("/");
        if (indexParts.length > 1) {
          const indexFolder = indexParts.slice(0, -1).join("/");
          if (!this.app.vault.getAbstractFileByPath(indexFolder)) {
            await this.app.vault.createFolder(indexFolder);
          }
        }
        await this.app.vault.create(indexFilePath, "# Wiki Index\n\n" + indexLine);
      }
      new import_obsidian3.Notice(`Successfully ingested ${file.name} to ${newFilePath}`);
    } catch (e) {
      console.error("Ingestion error:", e);
      new import_obsidian3.Notice(`Failed to ingest ${file.name}: ${e.message}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var LLMWikiForgeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Provider").setDesc("Choose your LLM provider").addDropdown((drop) => drop.addOption("openai", "OpenAI").addOption("anthropic", "Anthropic").addOption("ollama", "Ollama (Local)").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.provider === "ollama") {
      new import_obsidian3.Setting(containerEl).setName("Ollama Endpoint").setDesc("Default is http://localhost:11434").addText((text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaEndpoint).onChange(async (value) => {
        this.plugin.settings.ollamaEndpoint = value;
        await this.plugin.saveSettings();
      }));
    } else {
      new import_obsidian3.Setting(containerEl).setName("API Key").setDesc("Your API key for the chosen provider").addText((text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian3.Setting(containerEl).setName("Model").setDesc("Model to use (e.g. gpt-4o, claude-3-5-sonnet-20240620)").addText((text) => text.setPlaceholder("Enter model name").setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Directory & File Settings" });
    new import_obsidian3.Setting(containerEl).setName("Source Folder").setDesc("Folder containing raw sources to ingest (e.g., _source)").addText((text) => text.setPlaceholder("_source").setValue(this.plugin.settings.sourceFolder).onChange(async (value) => {
      this.plugin.settings.sourceFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Wiki Folder").setDesc("Folder where generated wiki pages will be saved").addText((text) => text.setPlaceholder("wiki").setValue(this.plugin.settings.wikiFolder).onChange(async (value) => {
      this.plugin.settings.wikiFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Index File").setDesc("Path to the index file (e.g., wiki/index.md)").addText((text) => text.setPlaceholder("wiki/index.md").setValue(this.plugin.settings.indexFile).onChange(async (value) => {
      this.plugin.settings.indexFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Log File").setDesc("Path to the log file (e.g., wiki/log.md)").addText((text) => text.setPlaceholder("wiki/log.md").setValue(this.plugin.settings.logFile).onChange(async (value) => {
      this.plugin.settings.logFile = value;
      await this.plugin.saveSettings();
    }));
  }
};
